// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bases.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countBasesByCorporateNumber = `-- name: CountBasesByCorporateNumber :one
SELECT COUNT(*) FROM bases
WHERE corporate_number = $1
`

func (q *Queries) CountBasesByCorporateNumber(ctx context.Context, corporateNumber string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBasesByCorporateNumber, corporateNumber)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBase = `-- name: CreateBase :one

INSERT INTO bases (
    id,
    corporation_id,
    corporate_number,
    base_name,
    country_code,
    postal_code,
    location,
    phone_number,
    fax_number,
    data_obtained_at,
    data_source_url,
    is_head_office
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, corporation_id, corporate_number, base_name, country_code, postal_code, location, phone_number, fax_number, data_obtained_at, data_source_url, is_head_office, created_at, updated_at
`

type CreateBaseParams struct {
	ID              uuid.UUID      `json:"id"`
	CorporationID   uuid.UUID      `json:"corporation_id"`
	CorporateNumber string         `json:"corporate_number"`
	BaseName        sql.NullString `json:"base_name"`
	CountryCode     string         `json:"country_code"`
	PostalCode      sql.NullString `json:"postal_code"`
	Location        sql.NullString `json:"location"`
	PhoneNumber     sql.NullString `json:"phone_number"`
	FaxNumber       sql.NullString `json:"fax_number"`
	DataObtainedAt  time.Time      `json:"data_obtained_at"`
	DataSourceUrl   string         `json:"data_source_url"`
	IsHeadOffice    bool           `json:"is_head_office"`
}

// db/queries/bases.sql
// Base/Branch management queries
func (q *Queries) CreateBase(ctx context.Context, arg CreateBaseParams) (Basis, error) {
	row := q.db.QueryRowContext(ctx, createBase,
		arg.ID,
		arg.CorporationID,
		arg.CorporateNumber,
		arg.BaseName,
		arg.CountryCode,
		arg.PostalCode,
		arg.Location,
		arg.PhoneNumber,
		arg.FaxNumber,
		arg.DataObtainedAt,
		arg.DataSourceUrl,
		arg.IsHeadOffice,
	)
	var i Basis
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.CorporateNumber,
		&i.BaseName,
		&i.CountryCode,
		&i.PostalCode,
		&i.Location,
		&i.PhoneNumber,
		&i.FaxNumber,
		&i.DataObtainedAt,
		&i.DataSourceUrl,
		&i.IsHeadOffice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBaseBatch = `-- name: CreateBaseBatch :exec
INSERT INTO bases (
    id,
    corporation_id,
    corporate_number,
    base_name,
    country_code,
    postal_code,
    location,
    phone_number,
    fax_number,
    data_obtained_at,
    data_source_url,
    is_head_office
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateBaseBatchParams struct {
	ID              uuid.UUID      `json:"id"`
	CorporationID   uuid.UUID      `json:"corporation_id"`
	CorporateNumber string         `json:"corporate_number"`
	BaseName        sql.NullString `json:"base_name"`
	CountryCode     string         `json:"country_code"`
	PostalCode      sql.NullString `json:"postal_code"`
	Location        sql.NullString `json:"location"`
	PhoneNumber     sql.NullString `json:"phone_number"`
	FaxNumber       sql.NullString `json:"fax_number"`
	DataObtainedAt  time.Time      `json:"data_obtained_at"`
	DataSourceUrl   string         `json:"data_source_url"`
	IsHeadOffice    bool           `json:"is_head_office"`
}

func (q *Queries) CreateBaseBatch(ctx context.Context, arg CreateBaseBatchParams) error {
	_, err := q.db.ExecContext(ctx, createBaseBatch,
		arg.ID,
		arg.CorporationID,
		arg.CorporateNumber,
		arg.BaseName,
		arg.CountryCode,
		arg.PostalCode,
		arg.Location,
		arg.PhoneNumber,
		arg.FaxNumber,
		arg.DataObtainedAt,
		arg.DataSourceUrl,
		arg.IsHeadOffice,
	)
	return err
}

const deleteBase = `-- name: DeleteBase :exec
DELETE FROM bases
WHERE id = $1
`

func (q *Queries) DeleteBase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBase, id)
	return err
}

const deleteBasesByCorporationID = `-- name: DeleteBasesByCorporationID :exec
DELETE FROM bases
WHERE corporation_id = $1
`

func (q *Queries) DeleteBasesByCorporationID(ctx context.Context, corporationID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBasesByCorporationID, corporationID)
	return err
}

const getBaseByID = `-- name: GetBaseByID :one
SELECT id, corporation_id, corporate_number, base_name, country_code, postal_code, location, phone_number, fax_number, data_obtained_at, data_source_url, is_head_office, created_at, updated_at FROM bases
WHERE id = $1
`

func (q *Queries) GetBaseByID(ctx context.Context, id uuid.UUID) (Basis, error) {
	row := q.db.QueryRowContext(ctx, getBaseByID, id)
	var i Basis
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.CorporateNumber,
		&i.BaseName,
		&i.CountryCode,
		&i.PostalCode,
		&i.Location,
		&i.PhoneNumber,
		&i.FaxNumber,
		&i.DataObtainedAt,
		&i.DataSourceUrl,
		&i.IsHeadOffice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBasesByCorporateNumber = `-- name: GetBasesByCorporateNumber :many
SELECT id, corporation_id, corporate_number, base_name, country_code, postal_code, location, phone_number, fax_number, data_obtained_at, data_source_url, is_head_office, created_at, updated_at FROM bases
WHERE corporate_number = $1
ORDER BY is_head_office DESC, base_name ASC
`

func (q *Queries) GetBasesByCorporateNumber(ctx context.Context, corporateNumber string) ([]Basis, error) {
	rows, err := q.db.QueryContext(ctx, getBasesByCorporateNumber, corporateNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Basis
	for rows.Next() {
		var i Basis
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.CorporateNumber,
			&i.BaseName,
			&i.CountryCode,
			&i.PostalCode,
			&i.Location,
			&i.PhoneNumber,
			&i.FaxNumber,
			&i.DataObtainedAt,
			&i.DataSourceUrl,
			&i.IsHeadOffice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBasesByCorporationID = `-- name: GetBasesByCorporationID :many
SELECT id, corporation_id, corporate_number, base_name, country_code, postal_code, location, phone_number, fax_number, data_obtained_at, data_source_url, is_head_office, created_at, updated_at FROM bases
WHERE corporation_id = $1
ORDER BY is_head_office DESC, base_name ASC
`

func (q *Queries) GetBasesByCorporationID(ctx context.Context, corporationID uuid.UUID) ([]Basis, error) {
	rows, err := q.db.QueryContext(ctx, getBasesByCorporationID, corporationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Basis
	for rows.Next() {
		var i Basis
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.CorporateNumber,
			&i.BaseName,
			&i.CountryCode,
			&i.PostalCode,
			&i.Location,
			&i.PhoneNumber,
			&i.FaxNumber,
			&i.DataObtainedAt,
			&i.DataSourceUrl,
			&i.IsHeadOffice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBasesByCountry = `-- name: GetBasesByCountry :many
SELECT id, corporation_id, corporate_number, base_name, country_code, postal_code, location, phone_number, fax_number, data_obtained_at, data_source_url, is_head_office, created_at, updated_at FROM bases
WHERE country_code = $1
ORDER BY base_name ASC
LIMIT $2 OFFSET $3
`

type GetBasesByCountryParams struct {
	CountryCode string `json:"country_code"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) GetBasesByCountry(ctx context.Context, arg GetBasesByCountryParams) ([]Basis, error) {
	rows, err := q.db.QueryContext(ctx, getBasesByCountry, arg.CountryCode, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Basis
	for rows.Next() {
		var i Basis
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.CorporateNumber,
			&i.BaseName,
			&i.CountryCode,
			&i.PostalCode,
			&i.Location,
			&i.PhoneNumber,
			&i.FaxNumber,
			&i.DataObtainedAt,
			&i.DataSourceUrl,
			&i.IsHeadOffice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHeadOfficeByCorporateNumber = `-- name: GetHeadOfficeByCorporateNumber :one
SELECT id, corporation_id, corporate_number, base_name, country_code, postal_code, location, phone_number, fax_number, data_obtained_at, data_source_url, is_head_office, created_at, updated_at FROM bases
WHERE corporate_number = $1 AND is_head_office = true
LIMIT 1
`

func (q *Queries) GetHeadOfficeByCorporateNumber(ctx context.Context, corporateNumber string) (Basis, error) {
	row := q.db.QueryRowContext(ctx, getHeadOfficeByCorporateNumber, corporateNumber)
	var i Basis
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.CorporateNumber,
		&i.BaseName,
		&i.CountryCode,
		&i.PostalCode,
		&i.Location,
		&i.PhoneNumber,
		&i.FaxNumber,
		&i.DataObtainedAt,
		&i.DataSourceUrl,
		&i.IsHeadOffice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHeadOfficesByCorporateNumbers = `-- name: GetHeadOfficesByCorporateNumbers :many
SELECT id, corporation_id, corporate_number, base_name, country_code, postal_code, location, phone_number, fax_number, data_obtained_at, data_source_url, is_head_office, created_at, updated_at FROM bases
WHERE corporate_number = ANY($1::char(13)[])
AND is_head_office = true
ORDER BY corporate_number
`

func (q *Queries) GetHeadOfficesByCorporateNumbers(ctx context.Context, dollar_1 []string) ([]Basis, error) {
	rows, err := q.db.QueryContext(ctx, getHeadOfficesByCorporateNumbers, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Basis
	for rows.Next() {
		var i Basis
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.CorporateNumber,
			&i.BaseName,
			&i.CountryCode,
			&i.PostalCode,
			&i.Location,
			&i.PhoneNumber,
			&i.FaxNumber,
			&i.DataObtainedAt,
			&i.DataSourceUrl,
			&i.IsHeadOffice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllBases = `-- name: ListAllBases :many
SELECT id, corporation_id, corporate_number, base_name, country_code, postal_code, location, phone_number, fax_number, data_obtained_at, data_source_url, is_head_office, created_at, updated_at FROM bases
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllBasesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllBases(ctx context.Context, arg ListAllBasesParams) ([]Basis, error) {
	rows, err := q.db.QueryContext(ctx, listAllBases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Basis
	for rows.Next() {
		var i Basis
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.CorporateNumber,
			&i.BaseName,
			&i.CountryCode,
			&i.PostalCode,
			&i.Location,
			&i.PhoneNumber,
			&i.FaxNumber,
			&i.DataObtainedAt,
			&i.DataSourceUrl,
			&i.IsHeadOffice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBasesByName = `-- name: SearchBasesByName :many
SELECT id, corporation_id, corporate_number, base_name, country_code, postal_code, location, phone_number, fax_number, data_obtained_at, data_source_url, is_head_office, created_at, updated_at FROM bases
WHERE base_name ILIKE '%' || $1 || '%'
ORDER BY base_name ASC
LIMIT $2 OFFSET $3
`

type SearchBasesByNameParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) SearchBasesByName(ctx context.Context, arg SearchBasesByNameParams) ([]Basis, error) {
	rows, err := q.db.QueryContext(ctx, searchBasesByName, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Basis
	for rows.Next() {
		var i Basis
		if err := rows.Scan(
			&i.ID,
			&i.CorporationID,
			&i.CorporateNumber,
			&i.BaseName,
			&i.CountryCode,
			&i.PostalCode,
			&i.Location,
			&i.PhoneNumber,
			&i.FaxNumber,
			&i.DataObtainedAt,
			&i.DataSourceUrl,
			&i.IsHeadOffice,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBase = `-- name: UpdateBase :one
UPDATE bases
SET 
    base_name = $2,
    country_code = $3,
    postal_code = $4,
    location = $5,
    phone_number = $6,
    fax_number = $7,
    data_obtained_at = $8,
    data_source_url = $9,
    is_head_office = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING id, corporation_id, corporate_number, base_name, country_code, postal_code, location, phone_number, fax_number, data_obtained_at, data_source_url, is_head_office, created_at, updated_at
`

type UpdateBaseParams struct {
	ID             uuid.UUID      `json:"id"`
	BaseName       sql.NullString `json:"base_name"`
	CountryCode    string         `json:"country_code"`
	PostalCode     sql.NullString `json:"postal_code"`
	Location       sql.NullString `json:"location"`
	PhoneNumber    sql.NullString `json:"phone_number"`
	FaxNumber      sql.NullString `json:"fax_number"`
	DataObtainedAt time.Time      `json:"data_obtained_at"`
	DataSourceUrl  string         `json:"data_source_url"`
	IsHeadOffice   bool           `json:"is_head_office"`
}

func (q *Queries) UpdateBase(ctx context.Context, arg UpdateBaseParams) (Basis, error) {
	row := q.db.QueryRowContext(ctx, updateBase,
		arg.ID,
		arg.BaseName,
		arg.CountryCode,
		arg.PostalCode,
		arg.Location,
		arg.PhoneNumber,
		arg.FaxNumber,
		arg.DataObtainedAt,
		arg.DataSourceUrl,
		arg.IsHeadOffice,
	)
	var i Basis
	err := row.Scan(
		&i.ID,
		&i.CorporationID,
		&i.CorporateNumber,
		&i.BaseName,
		&i.CountryCode,
		&i.PostalCode,
		&i.Location,
		&i.PhoneNumber,
		&i.FaxNumber,
		&i.DataObtainedAt,
		&i.DataSourceUrl,
		&i.IsHeadOffice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
