// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: corporations.sql

package db

import (
	"context"
	"database/sql"
)

const countCorporationsWithFilter = `-- name: CountCorporationsWithFilter :one
SELECT COUNT(*) 
FROM corporations 
WHERE ($1 = '' OR corporate_number = $1)
  AND ($2 = '' OR name ILIKE '%' || $2 || '%')
  AND ($3 = '' OR prefecture_code = $3)
  AND ($4 = '' OR status = $4)
  AND ($5 = '' OR corporate_type = $5)
`

type CountCorporationsWithFilterParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
}

func (q *Queries) CountCorporationsWithFilter(ctx context.Context, arg CountCorporationsWithFilterParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCorporationsWithFilter,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCorporation = `-- name: CreateCorporation :one
INSERT INTO corporations (
    corporate_number, name, name_kana, english_name, postal_code, address,
    prefecture_code, city_code, founding_date, status, corporate_type,
    capital_stock, employee_number, representative, business_description,
    industry, website, phone, email, last_updated
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
RETURNING id, corporate_number, name, name_kana, english_name, postal_code, address, 
          prefecture_code, city_code, founding_date, status, corporate_type, 
          capital_stock, employee_number, representative, business_description, 
          industry, website, phone, email, last_updated, created_at, updated_at
`

type CreateCorporationParams struct {
	CorporateNumber     string         `json:"corporate_number"`
	Name                string         `json:"name"`
	NameKana            sql.NullString `json:"name_kana"`
	EnglishName         sql.NullString `json:"english_name"`
	PostalCode          sql.NullString `json:"postal_code"`
	Address             sql.NullString `json:"address"`
	PrefectureCode      sql.NullString `json:"prefecture_code"`
	CityCode            sql.NullString `json:"city_code"`
	FoundingDate        sql.NullTime   `json:"founding_date"`
	Status              string         `json:"status"`
	CorporateType       sql.NullString `json:"corporate_type"`
	CapitalStock        sql.NullInt64  `json:"capital_stock"`
	EmployeeNumber      sql.NullInt32  `json:"employee_number"`
	Representative      sql.NullString `json:"representative"`
	BusinessDescription sql.NullString `json:"business_description"`
	Industry            sql.NullString `json:"industry"`
	Website             sql.NullString `json:"website"`
	Phone               sql.NullString `json:"phone"`
	Email               sql.NullString `json:"email"`
	LastUpdated         sql.NullTime   `json:"last_updated"`
}

func (q *Queries) CreateCorporation(ctx context.Context, arg CreateCorporationParams) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, createCorporation,
		arg.CorporateNumber,
		arg.Name,
		arg.NameKana,
		arg.EnglishName,
		arg.PostalCode,
		arg.Address,
		arg.PrefectureCode,
		arg.CityCode,
		arg.FoundingDate,
		arg.Status,
		arg.CorporateType,
		arg.CapitalStock,
		arg.EmployeeNumber,
		arg.Representative,
		arg.BusinessDescription,
		arg.Industry,
		arg.Website,
		arg.Phone,
		arg.Email,
		arg.LastUpdated,
	)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.Name,
		&i.NameKana,
		&i.EnglishName,
		&i.PostalCode,
		&i.Address,
		&i.PrefectureCode,
		&i.CityCode,
		&i.FoundingDate,
		&i.Status,
		&i.CorporateType,
		&i.CapitalStock,
		&i.EmployeeNumber,
		&i.Representative,
		&i.BusinessDescription,
		&i.Industry,
		&i.Website,
		&i.Phone,
		&i.Email,
		&i.LastUpdated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCorporation = `-- name: DeleteCorporation :exec
DELETE FROM corporations
WHERE id = $1
`

func (q *Queries) DeleteCorporation(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCorporation, id)
	return err
}

const deleteCorporationByCorporateNumber = `-- name: DeleteCorporationByCorporateNumber :exec
DELETE FROM corporations
WHERE corporate_number = $1
`

func (q *Queries) DeleteCorporationByCorporateNumber(ctx context.Context, corporateNumber string) error {
	_, err := q.db.ExecContext(ctx, deleteCorporationByCorporateNumber, corporateNumber)
	return err
}

const getCorporationByCorporateNumber = `-- name: GetCorporationByCorporateNumber :one
SELECT id, corporate_number, name, name_kana, english_name, postal_code, address, 
       prefecture_code, city_code, founding_date, status, corporate_type, 
       capital_stock, employee_number, representative, business_description, 
       industry, website, phone, email, last_updated, created_at, updated_at 
FROM corporations 
WHERE corporate_number = $1 LIMIT 1
`

func (q *Queries) GetCorporationByCorporateNumber(ctx context.Context, corporateNumber string) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, getCorporationByCorporateNumber, corporateNumber)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.Name,
		&i.NameKana,
		&i.EnglishName,
		&i.PostalCode,
		&i.Address,
		&i.PrefectureCode,
		&i.CityCode,
		&i.FoundingDate,
		&i.Status,
		&i.CorporateType,
		&i.CapitalStock,
		&i.EmployeeNumber,
		&i.Representative,
		&i.BusinessDescription,
		&i.Industry,
		&i.Website,
		&i.Phone,
		&i.Email,
		&i.LastUpdated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCorporationByID = `-- name: GetCorporationByID :one
SELECT id, corporate_number, name, name_kana, english_name, postal_code, address, 
       prefecture_code, city_code, founding_date, status, corporate_type, 
       capital_stock, employee_number, representative, business_description, 
       industry, website, phone, email, last_updated, created_at, updated_at 
FROM corporations 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCorporationByID(ctx context.Context, id int32) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, getCorporationByID, id)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.Name,
		&i.NameKana,
		&i.EnglishName,
		&i.PostalCode,
		&i.Address,
		&i.PrefectureCode,
		&i.CityCode,
		&i.FoundingDate,
		&i.Status,
		&i.CorporateType,
		&i.CapitalStock,
		&i.EmployeeNumber,
		&i.Representative,
		&i.BusinessDescription,
		&i.Industry,
		&i.Website,
		&i.Phone,
		&i.Email,
		&i.LastUpdated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCorporations = `-- name: GetCorporations :many
SELECT id, corporate_number, name, name_kana, english_name, postal_code, address, 
       prefecture_code, city_code, founding_date, status, corporate_type, 
       capital_stock, employee_number, representative, business_description, 
       industry, website, phone, email, last_updated, created_at, updated_at 
FROM corporations 
ORDER BY created_at DESC
`

func (q *Queries) GetCorporations(ctx context.Context) ([]Corporation, error) {
	rows, err := q.db.QueryContext(ctx, getCorporations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Corporation
	for rows.Next() {
		var i Corporation
		if err := rows.Scan(
			&i.ID,
			&i.CorporateNumber,
			&i.Name,
			&i.NameKana,
			&i.EnglishName,
			&i.PostalCode,
			&i.Address,
			&i.PrefectureCode,
			&i.CityCode,
			&i.FoundingDate,
			&i.Status,
			&i.CorporateType,
			&i.CapitalStock,
			&i.EmployeeNumber,
			&i.Representative,
			&i.BusinessDescription,
			&i.Industry,
			&i.Website,
			&i.Phone,
			&i.Email,
			&i.LastUpdated,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCorporationsWithFilter = `-- name: GetCorporationsWithFilter :many
SELECT id, corporate_number, name, name_kana, english_name, postal_code, address, 
       prefecture_code, city_code, founding_date, status, corporate_type, 
       capital_stock, employee_number, representative, business_description, 
       industry, website, phone, email, last_updated, created_at, updated_at 
FROM corporations 
WHERE ($1 = '' OR corporate_number = $1)
  AND ($2 = '' OR name ILIKE '%' || $2 || '%')
  AND ($3 = '' OR prefecture_code = $3)
  AND ($4 = '' OR status = $4)
  AND ($5 = '' OR corporate_type = $5)
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type GetCorporationsWithFilterParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetCorporationsWithFilter(ctx context.Context, arg GetCorporationsWithFilterParams) ([]Corporation, error) {
	rows, err := q.db.QueryContext(ctx, getCorporationsWithFilter,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Corporation
	for rows.Next() {
		var i Corporation
		if err := rows.Scan(
			&i.ID,
			&i.CorporateNumber,
			&i.Name,
			&i.NameKana,
			&i.EnglishName,
			&i.PostalCode,
			&i.Address,
			&i.PrefectureCode,
			&i.CityCode,
			&i.FoundingDate,
			&i.Status,
			&i.CorporateType,
			&i.CapitalStock,
			&i.EmployeeNumber,
			&i.Representative,
			&i.BusinessDescription,
			&i.Industry,
			&i.Website,
			&i.Phone,
			&i.Email,
			&i.LastUpdated,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCorporation = `-- name: UpdateCorporation :one
UPDATE corporations
SET name = $2, name_kana = $3, english_name = $4, postal_code = $5, address = $6,
    prefecture_code = $7, city_code = $8, founding_date = $9, status = $10, 
    corporate_type = $11, capital_stock = $12, employee_number = $13, 
    representative = $14, business_description = $15, industry = $16, 
    website = $17, phone = $18, email = $19, last_updated = $20, updated_at = NOW()
WHERE id = $1
RETURNING id, corporate_number, name, name_kana, english_name, postal_code, address, 
          prefecture_code, city_code, founding_date, status, corporate_type, 
          capital_stock, employee_number, representative, business_description, 
          industry, website, phone, email, last_updated, created_at, updated_at
`

type UpdateCorporationParams struct {
	ID                  int32          `json:"id"`
	Name                string         `json:"name"`
	NameKana            sql.NullString `json:"name_kana"`
	EnglishName         sql.NullString `json:"english_name"`
	PostalCode          sql.NullString `json:"postal_code"`
	Address             sql.NullString `json:"address"`
	PrefectureCode      sql.NullString `json:"prefecture_code"`
	CityCode            sql.NullString `json:"city_code"`
	FoundingDate        sql.NullTime   `json:"founding_date"`
	Status              string         `json:"status"`
	CorporateType       sql.NullString `json:"corporate_type"`
	CapitalStock        sql.NullInt64  `json:"capital_stock"`
	EmployeeNumber      sql.NullInt32  `json:"employee_number"`
	Representative      sql.NullString `json:"representative"`
	BusinessDescription sql.NullString `json:"business_description"`
	Industry            sql.NullString `json:"industry"`
	Website             sql.NullString `json:"website"`
	Phone               sql.NullString `json:"phone"`
	Email               sql.NullString `json:"email"`
	LastUpdated         sql.NullTime   `json:"last_updated"`
}

func (q *Queries) UpdateCorporation(ctx context.Context, arg UpdateCorporationParams) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, updateCorporation,
		arg.ID,
		arg.Name,
		arg.NameKana,
		arg.EnglishName,
		arg.PostalCode,
		arg.Address,
		arg.PrefectureCode,
		arg.CityCode,
		arg.FoundingDate,
		arg.Status,
		arg.CorporateType,
		arg.CapitalStock,
		arg.EmployeeNumber,
		arg.Representative,
		arg.BusinessDescription,
		arg.Industry,
		arg.Website,
		arg.Phone,
		arg.Email,
		arg.LastUpdated,
	)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.Name,
		&i.NameKana,
		&i.EnglishName,
		&i.PostalCode,
		&i.Address,
		&i.PrefectureCode,
		&i.CityCode,
		&i.FoundingDate,
		&i.Status,
		&i.CorporateType,
		&i.CapitalStock,
		&i.EmployeeNumber,
		&i.Representative,
		&i.BusinessDescription,
		&i.Industry,
		&i.Website,
		&i.Phone,
		&i.Email,
		&i.LastUpdated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCorporation = `-- name: UpsertCorporation :one
INSERT INTO corporations (
    corporate_number, name, name_kana, english_name, postal_code, address,
    prefecture_code, city_code, founding_date, status, corporate_type,
    capital_stock, employee_number, representative, business_description,
    industry, website, phone, email, last_updated
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20
)
ON CONFLICT (corporate_number)
DO UPDATE SET
    name = EXCLUDED.name,
    name_kana = EXCLUDED.name_kana,
    english_name = EXCLUDED.english_name,
    postal_code = EXCLUDED.postal_code,
    address = EXCLUDED.address,
    prefecture_code = EXCLUDED.prefecture_code,
    city_code = EXCLUDED.city_code,
    founding_date = EXCLUDED.founding_date,
    status = EXCLUDED.status,
    corporate_type = EXCLUDED.corporate_type,
    capital_stock = EXCLUDED.capital_stock,
    employee_number = EXCLUDED.employee_number,
    representative = EXCLUDED.representative,
    business_description = EXCLUDED.business_description,
    industry = EXCLUDED.industry,
    website = EXCLUDED.website,
    phone = EXCLUDED.phone,
    email = EXCLUDED.email,
    last_updated = EXCLUDED.last_updated,
    updated_at = NOW()
RETURNING id, corporate_number, name, name_kana, english_name, postal_code, address, 
          prefecture_code, city_code, founding_date, status, corporate_type, 
          capital_stock, employee_number, representative, business_description, 
          industry, website, phone, email, last_updated, created_at, updated_at
`

type UpsertCorporationParams struct {
	CorporateNumber     string         `json:"corporate_number"`
	Name                string         `json:"name"`
	NameKana            sql.NullString `json:"name_kana"`
	EnglishName         sql.NullString `json:"english_name"`
	PostalCode          sql.NullString `json:"postal_code"`
	Address             sql.NullString `json:"address"`
	PrefectureCode      sql.NullString `json:"prefecture_code"`
	CityCode            sql.NullString `json:"city_code"`
	FoundingDate        sql.NullTime   `json:"founding_date"`
	Status              string         `json:"status"`
	CorporateType       sql.NullString `json:"corporate_type"`
	CapitalStock        sql.NullInt64  `json:"capital_stock"`
	EmployeeNumber      sql.NullInt32  `json:"employee_number"`
	Representative      sql.NullString `json:"representative"`
	BusinessDescription sql.NullString `json:"business_description"`
	Industry            sql.NullString `json:"industry"`
	Website             sql.NullString `json:"website"`
	Phone               sql.NullString `json:"phone"`
	Email               sql.NullString `json:"email"`
	LastUpdated         sql.NullTime   `json:"last_updated"`
}

func (q *Queries) UpsertCorporation(ctx context.Context, arg UpsertCorporationParams) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, upsertCorporation,
		arg.CorporateNumber,
		arg.Name,
		arg.NameKana,
		arg.EnglishName,
		arg.PostalCode,
		arg.Address,
		arg.PrefectureCode,
		arg.CityCode,
		arg.FoundingDate,
		arg.Status,
		arg.CorporateType,
		arg.CapitalStock,
		arg.EmployeeNumber,
		arg.Representative,
		arg.BusinessDescription,
		arg.Industry,
		arg.Website,
		arg.Phone,
		arg.Email,
		arg.LastUpdated,
	)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.Name,
		&i.NameKana,
		&i.EnglishName,
		&i.PostalCode,
		&i.Address,
		&i.PrefectureCode,
		&i.CityCode,
		&i.FoundingDate,
		&i.Status,
		&i.CorporateType,
		&i.CapitalStock,
		&i.EmployeeNumber,
		&i.Representative,
		&i.BusinessDescription,
		&i.Industry,
		&i.Website,
		&i.Phone,
		&i.Email,
		&i.LastUpdated,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
