// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: corporations.sql

package db

import (
	"context"
	"database/sql"
)

const countCorporationsWithFilter = `-- name: CountCorporationsWithFilter :one
SELECT COUNT(*) 
FROM corporations 
WHERE ($1 = '' OR corporate_number = $1)
  AND ($2 = '' OR name ILIKE '%' || $2 || '%')
  AND ($3 = '' OR location ILIKE '%' || $3 || '%')
  AND ($4 = '' OR status = $4)
`

type CountCorporationsWithFilterParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
}

func (q *Queries) CountCorporationsWithFilter(ctx context.Context, arg CountCorporationsWithFilterParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCorporationsWithFilter,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCorporation = `-- name: CreateCorporation :one
INSERT INTO corporations (
    corporate_number, name, kana, name_en, postal_code, location,
    status, close_date, close_cause, representative_name, representative_position,
    date_of_establishment, founding_year, capital_stock, employee_number,
    company_size_male, company_size_female, business_items, business_summary,
    company_url, qualification_grade, number_of_activity, update_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
)
RETURNING id, corporate_number, name, kana, name_en, postal_code, location, 
          status, close_date, close_cause, representative_name, representative_position,
          date_of_establishment, founding_year, capital_stock, employee_number,
          company_size_male, company_size_female, business_items, business_summary,
          company_url, qualification_grade, number_of_activity, update_date,
          created_at, updated_at
`

type CreateCorporationParams struct {
	CorporateNumber        string         `json:"corporate_number"`
	Name                   string         `json:"name"`
	Kana                   sql.NullString `json:"kana"`
	NameEn                 sql.NullString `json:"name_en"`
	PostalCode             sql.NullString `json:"postal_code"`
	Location               sql.NullString `json:"location"`
	Status                 string         `json:"status"`
	CloseDate              sql.NullTime   `json:"close_date"`
	CloseCause             sql.NullString `json:"close_cause"`
	RepresentativeName     sql.NullString `json:"representative_name"`
	RepresentativePosition sql.NullString `json:"representative_position"`
	DateOfEstablishment    sql.NullTime   `json:"date_of_establishment"`
	FoundingYear           sql.NullInt32  `json:"founding_year"`
	CapitalStock           sql.NullInt64  `json:"capital_stock"`
	EmployeeNumber         sql.NullInt32  `json:"employee_number"`
	CompanySizeMale        sql.NullInt32  `json:"company_size_male"`
	CompanySizeFemale      sql.NullInt32  `json:"company_size_female"`
	BusinessItems          sql.NullString `json:"business_items"`
	BusinessSummary        sql.NullString `json:"business_summary"`
	CompanyUrl             sql.NullString `json:"company_url"`
	QualificationGrade     sql.NullString `json:"qualification_grade"`
	NumberOfActivity       sql.NullString `json:"number_of_activity"`
	UpdateDate             sql.NullTime   `json:"update_date"`
}

func (q *Queries) CreateCorporation(ctx context.Context, arg CreateCorporationParams) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, createCorporation,
		arg.CorporateNumber,
		arg.Name,
		arg.Kana,
		arg.NameEn,
		arg.PostalCode,
		arg.Location,
		arg.Status,
		arg.CloseDate,
		arg.CloseCause,
		arg.RepresentativeName,
		arg.RepresentativePosition,
		arg.DateOfEstablishment,
		arg.FoundingYear,
		arg.CapitalStock,
		arg.EmployeeNumber,
		arg.CompanySizeMale,
		arg.CompanySizeFemale,
		arg.BusinessItems,
		arg.BusinessSummary,
		arg.CompanyUrl,
		arg.QualificationGrade,
		arg.NumberOfActivity,
		arg.UpdateDate,
	)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.Name,
		&i.Kana,
		&i.NameEn,
		&i.PostalCode,
		&i.Location,
		&i.Status,
		&i.CloseDate,
		&i.CloseCause,
		&i.RepresentativeName,
		&i.RepresentativePosition,
		&i.DateOfEstablishment,
		&i.FoundingYear,
		&i.CapitalStock,
		&i.EmployeeNumber,
		&i.CompanySizeMale,
		&i.CompanySizeFemale,
		&i.BusinessItems,
		&i.BusinessSummary,
		&i.CompanyUrl,
		&i.QualificationGrade,
		&i.NumberOfActivity,
		&i.UpdateDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCorporation = `-- name: DeleteCorporation :exec
DELETE FROM corporations
WHERE id = $1
`

func (q *Queries) DeleteCorporation(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteCorporation, id)
	return err
}

const deleteCorporationByCorporateNumber = `-- name: DeleteCorporationByCorporateNumber :exec
DELETE FROM corporations
WHERE corporate_number = $1
`

func (q *Queries) DeleteCorporationByCorporateNumber(ctx context.Context, corporateNumber string) error {
	_, err := q.db.ExecContext(ctx, deleteCorporationByCorporateNumber, corporateNumber)
	return err
}

const getCorporationByCorporateNumber = `-- name: GetCorporationByCorporateNumber :one
SELECT id, corporate_number, name, kana, name_en, postal_code, location, 
       status, close_date, close_cause, representative_name, representative_position,
       date_of_establishment, founding_year, capital_stock, employee_number,
       company_size_male, company_size_female, business_items, business_summary,
       company_url, qualification_grade, number_of_activity, update_date,
       created_at, updated_at 
FROM corporations 
WHERE corporate_number = $1 LIMIT 1
`

func (q *Queries) GetCorporationByCorporateNumber(ctx context.Context, corporateNumber string) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, getCorporationByCorporateNumber, corporateNumber)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.Name,
		&i.Kana,
		&i.NameEn,
		&i.PostalCode,
		&i.Location,
		&i.Status,
		&i.CloseDate,
		&i.CloseCause,
		&i.RepresentativeName,
		&i.RepresentativePosition,
		&i.DateOfEstablishment,
		&i.FoundingYear,
		&i.CapitalStock,
		&i.EmployeeNumber,
		&i.CompanySizeMale,
		&i.CompanySizeFemale,
		&i.BusinessItems,
		&i.BusinessSummary,
		&i.CompanyUrl,
		&i.QualificationGrade,
		&i.NumberOfActivity,
		&i.UpdateDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCorporationByID = `-- name: GetCorporationByID :one
SELECT id, corporate_number, name, kana, name_en, postal_code, location, 
       status, close_date, close_cause, representative_name, representative_position,
       date_of_establishment, founding_year, capital_stock, employee_number,
       company_size_male, company_size_female, business_items, business_summary,
       company_url, qualification_grade, number_of_activity, update_date,
       created_at, updated_at 
FROM corporations 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCorporationByID(ctx context.Context, id int32) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, getCorporationByID, id)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.Name,
		&i.Kana,
		&i.NameEn,
		&i.PostalCode,
		&i.Location,
		&i.Status,
		&i.CloseDate,
		&i.CloseCause,
		&i.RepresentativeName,
		&i.RepresentativePosition,
		&i.DateOfEstablishment,
		&i.FoundingYear,
		&i.CapitalStock,
		&i.EmployeeNumber,
		&i.CompanySizeMale,
		&i.CompanySizeFemale,
		&i.BusinessItems,
		&i.BusinessSummary,
		&i.CompanyUrl,
		&i.QualificationGrade,
		&i.NumberOfActivity,
		&i.UpdateDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCorporations = `-- name: GetCorporations :many

SELECT id, corporate_number, name, kana, name_en, postal_code, location, 
       status, close_date, close_cause, representative_name, representative_position,
       date_of_establishment, founding_year, capital_stock, employee_number,
       company_size_male, company_size_female, business_items, business_summary,
       company_url, qualification_grade, number_of_activity, update_date,
       created_at, updated_at 
FROM corporations 
ORDER BY created_at DESC
`

// Updated for gBizINFO API compliance
func (q *Queries) GetCorporations(ctx context.Context) ([]Corporation, error) {
	rows, err := q.db.QueryContext(ctx, getCorporations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Corporation
	for rows.Next() {
		var i Corporation
		if err := rows.Scan(
			&i.ID,
			&i.CorporateNumber,
			&i.Name,
			&i.Kana,
			&i.NameEn,
			&i.PostalCode,
			&i.Location,
			&i.Status,
			&i.CloseDate,
			&i.CloseCause,
			&i.RepresentativeName,
			&i.RepresentativePosition,
			&i.DateOfEstablishment,
			&i.FoundingYear,
			&i.CapitalStock,
			&i.EmployeeNumber,
			&i.CompanySizeMale,
			&i.CompanySizeFemale,
			&i.BusinessItems,
			&i.BusinessSummary,
			&i.CompanyUrl,
			&i.QualificationGrade,
			&i.NumberOfActivity,
			&i.UpdateDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCorporationsWithFilter = `-- name: GetCorporationsWithFilter :many
SELECT id, corporate_number, name, kana, name_en, postal_code, location, 
       status, close_date, close_cause, representative_name, representative_position,
       date_of_establishment, founding_year, capital_stock, employee_number,
       company_size_male, company_size_female, business_items, business_summary,
       company_url, qualification_grade, number_of_activity, update_date,
       created_at, updated_at 
FROM corporations 
WHERE ($1 = '' OR corporate_number = $1)
  AND ($2 = '' OR name ILIKE '%' || $2 || '%')
  AND ($3 = '' OR location ILIKE '%' || $3 || '%')
  AND ($4 = '' OR status = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type GetCorporationsWithFilterParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetCorporationsWithFilter(ctx context.Context, arg GetCorporationsWithFilterParams) ([]Corporation, error) {
	rows, err := q.db.QueryContext(ctx, getCorporationsWithFilter,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Corporation
	for rows.Next() {
		var i Corporation
		if err := rows.Scan(
			&i.ID,
			&i.CorporateNumber,
			&i.Name,
			&i.Kana,
			&i.NameEn,
			&i.PostalCode,
			&i.Location,
			&i.Status,
			&i.CloseDate,
			&i.CloseCause,
			&i.RepresentativeName,
			&i.RepresentativePosition,
			&i.DateOfEstablishment,
			&i.FoundingYear,
			&i.CapitalStock,
			&i.EmployeeNumber,
			&i.CompanySizeMale,
			&i.CompanySizeFemale,
			&i.BusinessItems,
			&i.BusinessSummary,
			&i.CompanyUrl,
			&i.QualificationGrade,
			&i.NumberOfActivity,
			&i.UpdateDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCorporation = `-- name: UpdateCorporation :one
UPDATE corporations
SET name = $2, kana = $3, name_en = $4, postal_code = $5, location = $6,
    status = $7, close_date = $8, close_cause = $9, representative_name = $10,
    representative_position = $11, date_of_establishment = $12, founding_year = $13,
    capital_stock = $14, employee_number = $15, company_size_male = $16,
    company_size_female = $17, business_items = $18, business_summary = $19,
    company_url = $20, qualification_grade = $21, number_of_activity = $22,
    update_date = $23, updated_at = NOW()
WHERE id = $1
RETURNING id, corporate_number, name, kana, name_en, postal_code, location, 
          status, close_date, close_cause, representative_name, representative_position,
          date_of_establishment, founding_year, capital_stock, employee_number,
          company_size_male, company_size_female, business_items, business_summary,
          company_url, qualification_grade, number_of_activity, update_date,
          created_at, updated_at
`

type UpdateCorporationParams struct {
	ID                     int32          `json:"id"`
	Name                   string         `json:"name"`
	Kana                   sql.NullString `json:"kana"`
	NameEn                 sql.NullString `json:"name_en"`
	PostalCode             sql.NullString `json:"postal_code"`
	Location               sql.NullString `json:"location"`
	Status                 string         `json:"status"`
	CloseDate              sql.NullTime   `json:"close_date"`
	CloseCause             sql.NullString `json:"close_cause"`
	RepresentativeName     sql.NullString `json:"representative_name"`
	RepresentativePosition sql.NullString `json:"representative_position"`
	DateOfEstablishment    sql.NullTime   `json:"date_of_establishment"`
	FoundingYear           sql.NullInt32  `json:"founding_year"`
	CapitalStock           sql.NullInt64  `json:"capital_stock"`
	EmployeeNumber         sql.NullInt32  `json:"employee_number"`
	CompanySizeMale        sql.NullInt32  `json:"company_size_male"`
	CompanySizeFemale      sql.NullInt32  `json:"company_size_female"`
	BusinessItems          sql.NullString `json:"business_items"`
	BusinessSummary        sql.NullString `json:"business_summary"`
	CompanyUrl             sql.NullString `json:"company_url"`
	QualificationGrade     sql.NullString `json:"qualification_grade"`
	NumberOfActivity       sql.NullString `json:"number_of_activity"`
	UpdateDate             sql.NullTime   `json:"update_date"`
}

func (q *Queries) UpdateCorporation(ctx context.Context, arg UpdateCorporationParams) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, updateCorporation,
		arg.ID,
		arg.Name,
		arg.Kana,
		arg.NameEn,
		arg.PostalCode,
		arg.Location,
		arg.Status,
		arg.CloseDate,
		arg.CloseCause,
		arg.RepresentativeName,
		arg.RepresentativePosition,
		arg.DateOfEstablishment,
		arg.FoundingYear,
		arg.CapitalStock,
		arg.EmployeeNumber,
		arg.CompanySizeMale,
		arg.CompanySizeFemale,
		arg.BusinessItems,
		arg.BusinessSummary,
		arg.CompanyUrl,
		arg.QualificationGrade,
		arg.NumberOfActivity,
		arg.UpdateDate,
	)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.Name,
		&i.Kana,
		&i.NameEn,
		&i.PostalCode,
		&i.Location,
		&i.Status,
		&i.CloseDate,
		&i.CloseCause,
		&i.RepresentativeName,
		&i.RepresentativePosition,
		&i.DateOfEstablishment,
		&i.FoundingYear,
		&i.CapitalStock,
		&i.EmployeeNumber,
		&i.CompanySizeMale,
		&i.CompanySizeFemale,
		&i.BusinessItems,
		&i.BusinessSummary,
		&i.CompanyUrl,
		&i.QualificationGrade,
		&i.NumberOfActivity,
		&i.UpdateDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCorporation = `-- name: UpsertCorporation :one
INSERT INTO corporations (
    corporate_number, name, kana, name_en, postal_code, location,
    status, close_date, close_cause, representative_name, representative_position,
    date_of_establishment, founding_year, capital_stock, employee_number,
    company_size_male, company_size_female, business_items, business_summary,
    company_url, qualification_grade, number_of_activity, update_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23
)
ON CONFLICT (corporate_number)
DO UPDATE SET
    name = EXCLUDED.name,
    kana = EXCLUDED.kana,
    name_en = EXCLUDED.name_en,
    postal_code = EXCLUDED.postal_code,
    location = EXCLUDED.location,
    status = EXCLUDED.status,
    close_date = EXCLUDED.close_date,
    close_cause = EXCLUDED.close_cause,
    representative_name = EXCLUDED.representative_name,
    representative_position = EXCLUDED.representative_position,
    date_of_establishment = EXCLUDED.date_of_establishment,
    founding_year = EXCLUDED.founding_year,
    capital_stock = EXCLUDED.capital_stock,
    employee_number = EXCLUDED.employee_number,
    company_size_male = EXCLUDED.company_size_male,
    company_size_female = EXCLUDED.company_size_female,
    business_items = EXCLUDED.business_items,
    business_summary = EXCLUDED.business_summary,
    company_url = EXCLUDED.company_url,
    qualification_grade = EXCLUDED.qualification_grade,
    number_of_activity = EXCLUDED.number_of_activity,
    update_date = EXCLUDED.update_date,
    updated_at = NOW()
RETURNING id, corporate_number, name, kana, name_en, postal_code, location, 
          status, close_date, close_cause, representative_name, representative_position,
          date_of_establishment, founding_year, capital_stock, employee_number,
          company_size_male, company_size_female, business_items, business_summary,
          company_url, qualification_grade, number_of_activity, update_date,
          created_at, updated_at
`

type UpsertCorporationParams struct {
	CorporateNumber        string         `json:"corporate_number"`
	Name                   string         `json:"name"`
	Kana                   sql.NullString `json:"kana"`
	NameEn                 sql.NullString `json:"name_en"`
	PostalCode             sql.NullString `json:"postal_code"`
	Location               sql.NullString `json:"location"`
	Status                 string         `json:"status"`
	CloseDate              sql.NullTime   `json:"close_date"`
	CloseCause             sql.NullString `json:"close_cause"`
	RepresentativeName     sql.NullString `json:"representative_name"`
	RepresentativePosition sql.NullString `json:"representative_position"`
	DateOfEstablishment    sql.NullTime   `json:"date_of_establishment"`
	FoundingYear           sql.NullInt32  `json:"founding_year"`
	CapitalStock           sql.NullInt64  `json:"capital_stock"`
	EmployeeNumber         sql.NullInt32  `json:"employee_number"`
	CompanySizeMale        sql.NullInt32  `json:"company_size_male"`
	CompanySizeFemale      sql.NullInt32  `json:"company_size_female"`
	BusinessItems          sql.NullString `json:"business_items"`
	BusinessSummary        sql.NullString `json:"business_summary"`
	CompanyUrl             sql.NullString `json:"company_url"`
	QualificationGrade     sql.NullString `json:"qualification_grade"`
	NumberOfActivity       sql.NullString `json:"number_of_activity"`
	UpdateDate             sql.NullTime   `json:"update_date"`
}

func (q *Queries) UpsertCorporation(ctx context.Context, arg UpsertCorporationParams) (Corporation, error) {
	row := q.db.QueryRowContext(ctx, upsertCorporation,
		arg.CorporateNumber,
		arg.Name,
		arg.Kana,
		arg.NameEn,
		arg.PostalCode,
		arg.Location,
		arg.Status,
		arg.CloseDate,
		arg.CloseCause,
		arg.RepresentativeName,
		arg.RepresentativePosition,
		arg.DateOfEstablishment,
		arg.FoundingYear,
		arg.CapitalStock,
		arg.EmployeeNumber,
		arg.CompanySizeMale,
		arg.CompanySizeFemale,
		arg.BusinessItems,
		arg.BusinessSummary,
		arg.CompanyUrl,
		arg.QualificationGrade,
		arg.NumberOfActivity,
		arg.UpdateDate,
	)
	var i Corporation
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.Name,
		&i.Kana,
		&i.NameEn,
		&i.PostalCode,
		&i.Location,
		&i.Status,
		&i.CloseDate,
		&i.CloseCause,
		&i.RepresentativeName,
		&i.RepresentativePosition,
		&i.DateOfEstablishment,
		&i.FoundingYear,
		&i.CapitalStock,
		&i.EmployeeNumber,
		&i.CompanySizeMale,
		&i.CompanySizeFemale,
		&i.BusinessItems,
		&i.BusinessSummary,
		&i.CompanyUrl,
		&i.QualificationGrade,
		&i.NumberOfActivity,
		&i.UpdateDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
