// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Corporation struct {
	ID                     int32          `json:"id"`
	CorporateNumber        string         `json:"corporate_number"`
	Name                   string         `json:"name"`
	Kana                   sql.NullString `json:"kana"`
	NameEn                 sql.NullString `json:"name_en"`
	PostalCode             sql.NullString `json:"postal_code"`
	Location               sql.NullString `json:"location"`
	PrefectureCode         sql.NullString `json:"prefecture_code"`
	Status                 string         `json:"status"`
	CloseDate              sql.NullTime   `json:"close_date"`
	CloseCause             sql.NullString `json:"close_cause"`
	RepresentativeName     sql.NullString `json:"representative_name"`
	RepresentativePosition sql.NullString `json:"representative_position"`
	DateOfEstablishment    sql.NullTime   `json:"date_of_establishment"`
	FoundingYear           sql.NullInt32  `json:"founding_year"`
	CapitalStock           sql.NullInt64  `json:"capital_stock"`
	EmployeeNumber         sql.NullInt32  `json:"employee_number"`
	CompanySizeMale        sql.NullInt32  `json:"company_size_male"`
	CompanySizeFemale      sql.NullInt32  `json:"company_size_female"`
	BusinessItems          sql.NullString `json:"business_items"`
	BusinessSummary        sql.NullString `json:"business_summary"`
	CompanyUrl             sql.NullString `json:"company_url"`
	QualificationGrade     sql.NullString `json:"qualification_grade"`
	NumberOfActivity       sql.NullString `json:"number_of_activity"`
	UpdateDate             sql.NullTime   `json:"update_date"`
	CreatedAt              sql.NullTime   `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
}
