// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: finances.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countAllFinances = `-- name: CountAllFinances :one
SELECT COUNT(*) FROM finances
`

func (q *Queries) CountAllFinances(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllFinances)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFinances = `-- name: CountFinances :one
SELECT COUNT(*) FROM finances
`

func (q *Queries) CountFinances(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFinances)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFinance = `-- name: CreateFinance :exec
INSERT INTO finances (
    id,
    corporate_number,
    corporate_name_from_number,
    head_office_location_from_number,
    corporate_name,
    head_office_location,
    accounting_standards,
    business_year,
    period_number,
    sales_revenue,
    sales_revenue_unit,
    operating_revenue1,
    operating_revenue1_unit,
    operating_revenue2,
    operating_revenue2_unit,
    gross_operating_revenue,
    gross_operating_revenue_unit,
    ordinary_revenue,
    ordinary_revenue_unit,
    net_premiums_written,
    net_premiums_written_unit,
    ordinary_income,
    ordinary_income_unit,
    net_income,
    net_income_unit,
    capital_stock,
    capital_stock_unit,
    net_assets,
    net_assets_unit,
    total_assets,
    total_assets_unit,
    number_of_employees,
    number_of_employees_unit,
    major_shareholder1,
    shareholding_ratio1,
    major_shareholder2,
    shareholding_ratio2,
    major_shareholder3,
    shareholding_ratio3,
    major_shareholder4,
    shareholding_ratio4,
    major_shareholder5,
    shareholding_ratio5
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43
)
`

type CreateFinanceParams struct {
	ID                           uuid.UUID      `json:"id"`
	CorporateNumber              string         `json:"corporate_number"`
	CorporateNameFromNumber      sql.NullString `json:"corporate_name_from_number"`
	HeadOfficeLocationFromNumber sql.NullString `json:"head_office_location_from_number"`
	CorporateName                sql.NullString `json:"corporate_name"`
	HeadOfficeLocation           sql.NullString `json:"head_office_location"`
	AccountingStandards          sql.NullString `json:"accounting_standards"`
	BusinessYear                 sql.NullString `json:"business_year"`
	PeriodNumber                 sql.NullString `json:"period_number"`
	SalesRevenue                 sql.NullString `json:"sales_revenue"`
	SalesRevenueUnit             sql.NullString `json:"sales_revenue_unit"`
	OperatingRevenue1            sql.NullString `json:"operating_revenue1"`
	OperatingRevenue1Unit        sql.NullString `json:"operating_revenue1_unit"`
	OperatingRevenue2            sql.NullString `json:"operating_revenue2"`
	OperatingRevenue2Unit        sql.NullString `json:"operating_revenue2_unit"`
	GrossOperatingRevenue        sql.NullString `json:"gross_operating_revenue"`
	GrossOperatingRevenueUnit    sql.NullString `json:"gross_operating_revenue_unit"`
	OrdinaryRevenue              sql.NullString `json:"ordinary_revenue"`
	OrdinaryRevenueUnit          sql.NullString `json:"ordinary_revenue_unit"`
	NetPremiumsWritten           sql.NullString `json:"net_premiums_written"`
	NetPremiumsWrittenUnit       sql.NullString `json:"net_premiums_written_unit"`
	OrdinaryIncome               sql.NullString `json:"ordinary_income"`
	OrdinaryIncomeUnit           sql.NullString `json:"ordinary_income_unit"`
	NetIncome                    sql.NullString `json:"net_income"`
	NetIncomeUnit                sql.NullString `json:"net_income_unit"`
	CapitalStock                 sql.NullString `json:"capital_stock"`
	CapitalStockUnit             sql.NullString `json:"capital_stock_unit"`
	NetAssets                    sql.NullString `json:"net_assets"`
	NetAssetsUnit                sql.NullString `json:"net_assets_unit"`
	TotalAssets                  sql.NullString `json:"total_assets"`
	TotalAssetsUnit              sql.NullString `json:"total_assets_unit"`
	NumberOfEmployees            sql.NullString `json:"number_of_employees"`
	NumberOfEmployeesUnit        sql.NullString `json:"number_of_employees_unit"`
	MajorShareholder1            sql.NullString `json:"major_shareholder1"`
	ShareholdingRatio1           sql.NullString `json:"shareholding_ratio1"`
	MajorShareholder2            sql.NullString `json:"major_shareholder2"`
	ShareholdingRatio2           sql.NullString `json:"shareholding_ratio2"`
	MajorShareholder3            sql.NullString `json:"major_shareholder3"`
	ShareholdingRatio3           sql.NullString `json:"shareholding_ratio3"`
	MajorShareholder4            sql.NullString `json:"major_shareholder4"`
	ShareholdingRatio4           sql.NullString `json:"shareholding_ratio4"`
	MajorShareholder5            sql.NullString `json:"major_shareholder5"`
	ShareholdingRatio5           sql.NullString `json:"shareholding_ratio5"`
}

func (q *Queries) CreateFinance(ctx context.Context, arg CreateFinanceParams) error {
	_, err := q.db.ExecContext(ctx, createFinance,
		arg.ID,
		arg.CorporateNumber,
		arg.CorporateNameFromNumber,
		arg.HeadOfficeLocationFromNumber,
		arg.CorporateName,
		arg.HeadOfficeLocation,
		arg.AccountingStandards,
		arg.BusinessYear,
		arg.PeriodNumber,
		arg.SalesRevenue,
		arg.SalesRevenueUnit,
		arg.OperatingRevenue1,
		arg.OperatingRevenue1Unit,
		arg.OperatingRevenue2,
		arg.OperatingRevenue2Unit,
		arg.GrossOperatingRevenue,
		arg.GrossOperatingRevenueUnit,
		arg.OrdinaryRevenue,
		arg.OrdinaryRevenueUnit,
		arg.NetPremiumsWritten,
		arg.NetPremiumsWrittenUnit,
		arg.OrdinaryIncome,
		arg.OrdinaryIncomeUnit,
		arg.NetIncome,
		arg.NetIncomeUnit,
		arg.CapitalStock,
		arg.CapitalStockUnit,
		arg.NetAssets,
		arg.NetAssetsUnit,
		arg.TotalAssets,
		arg.TotalAssetsUnit,
		arg.NumberOfEmployees,
		arg.NumberOfEmployeesUnit,
		arg.MajorShareholder1,
		arg.ShareholdingRatio1,
		arg.MajorShareholder2,
		arg.ShareholdingRatio2,
		arg.MajorShareholder3,
		arg.ShareholdingRatio3,
		arg.MajorShareholder4,
		arg.ShareholdingRatio4,
		arg.MajorShareholder5,
		arg.ShareholdingRatio5,
	)
	return err
}

const deleteAllFinances = `-- name: DeleteAllFinances :exec
DELETE FROM finances
`

func (q *Queries) DeleteAllFinances(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllFinances)
	return err
}

const deleteFinancesByCorporateNumber = `-- name: DeleteFinancesByCorporateNumber :exec
DELETE FROM finances 
WHERE corporate_number = $1
`

func (q *Queries) DeleteFinancesByCorporateNumber(ctx context.Context, corporateNumber string) error {
	_, err := q.db.ExecContext(ctx, deleteFinancesByCorporateNumber, corporateNumber)
	return err
}

const getFinancesByBusinessYear = `-- name: GetFinancesByBusinessYear :many
SELECT id, corporate_number, corporate_name_from_number, head_office_location_from_number, corporate_name, head_office_location, accounting_standards, business_year, period_number, sales_revenue, sales_revenue_unit, operating_revenue1, operating_revenue1_unit, operating_revenue2, operating_revenue2_unit, gross_operating_revenue, gross_operating_revenue_unit, ordinary_revenue, ordinary_revenue_unit, net_premiums_written, net_premiums_written_unit, ordinary_income, ordinary_income_unit, net_income, net_income_unit, capital_stock, capital_stock_unit, net_assets, net_assets_unit, total_assets, total_assets_unit, number_of_employees, number_of_employees_unit, major_shareholder1, shareholding_ratio1, major_shareholder2, shareholding_ratio2, major_shareholder3, shareholding_ratio3, major_shareholder4, shareholding_ratio4, major_shareholder5, shareholding_ratio5, created_at, updated_at FROM finances 
WHERE business_year = $1
ORDER BY corporate_number
`

func (q *Queries) GetFinancesByBusinessYear(ctx context.Context, businessYear sql.NullString) ([]Finance, error) {
	rows, err := q.db.QueryContext(ctx, getFinancesByBusinessYear, businessYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finance
	for rows.Next() {
		var i Finance
		if err := rows.Scan(
			&i.ID,
			&i.CorporateNumber,
			&i.CorporateNameFromNumber,
			&i.HeadOfficeLocationFromNumber,
			&i.CorporateName,
			&i.HeadOfficeLocation,
			&i.AccountingStandards,
			&i.BusinessYear,
			&i.PeriodNumber,
			&i.SalesRevenue,
			&i.SalesRevenueUnit,
			&i.OperatingRevenue1,
			&i.OperatingRevenue1Unit,
			&i.OperatingRevenue2,
			&i.OperatingRevenue2Unit,
			&i.GrossOperatingRevenue,
			&i.GrossOperatingRevenueUnit,
			&i.OrdinaryRevenue,
			&i.OrdinaryRevenueUnit,
			&i.NetPremiumsWritten,
			&i.NetPremiumsWrittenUnit,
			&i.OrdinaryIncome,
			&i.OrdinaryIncomeUnit,
			&i.NetIncome,
			&i.NetIncomeUnit,
			&i.CapitalStock,
			&i.CapitalStockUnit,
			&i.NetAssets,
			&i.NetAssetsUnit,
			&i.TotalAssets,
			&i.TotalAssetsUnit,
			&i.NumberOfEmployees,
			&i.NumberOfEmployeesUnit,
			&i.MajorShareholder1,
			&i.ShareholdingRatio1,
			&i.MajorShareholder2,
			&i.ShareholdingRatio2,
			&i.MajorShareholder3,
			&i.ShareholdingRatio3,
			&i.MajorShareholder4,
			&i.ShareholdingRatio4,
			&i.MajorShareholder5,
			&i.ShareholdingRatio5,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinancesByCorporateNumber = `-- name: GetFinancesByCorporateNumber :many
SELECT id, corporate_number, corporate_name_from_number, head_office_location_from_number, corporate_name, head_office_location, accounting_standards, business_year, period_number, sales_revenue, sales_revenue_unit, operating_revenue1, operating_revenue1_unit, operating_revenue2, operating_revenue2_unit, gross_operating_revenue, gross_operating_revenue_unit, ordinary_revenue, ordinary_revenue_unit, net_premiums_written, net_premiums_written_unit, ordinary_income, ordinary_income_unit, net_income, net_income_unit, capital_stock, capital_stock_unit, net_assets, net_assets_unit, total_assets, total_assets_unit, number_of_employees, number_of_employees_unit, major_shareholder1, shareholding_ratio1, major_shareholder2, shareholding_ratio2, major_shareholder3, shareholding_ratio3, major_shareholder4, shareholding_ratio4, major_shareholder5, shareholding_ratio5, created_at, updated_at FROM finances 
WHERE corporate_number = $1
ORDER BY business_year DESC, period_number DESC
`

func (q *Queries) GetFinancesByCorporateNumber(ctx context.Context, corporateNumber string) ([]Finance, error) {
	rows, err := q.db.QueryContext(ctx, getFinancesByCorporateNumber, corporateNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finance
	for rows.Next() {
		var i Finance
		if err := rows.Scan(
			&i.ID,
			&i.CorporateNumber,
			&i.CorporateNameFromNumber,
			&i.HeadOfficeLocationFromNumber,
			&i.CorporateName,
			&i.HeadOfficeLocation,
			&i.AccountingStandards,
			&i.BusinessYear,
			&i.PeriodNumber,
			&i.SalesRevenue,
			&i.SalesRevenueUnit,
			&i.OperatingRevenue1,
			&i.OperatingRevenue1Unit,
			&i.OperatingRevenue2,
			&i.OperatingRevenue2Unit,
			&i.GrossOperatingRevenue,
			&i.GrossOperatingRevenueUnit,
			&i.OrdinaryRevenue,
			&i.OrdinaryRevenueUnit,
			&i.NetPremiumsWritten,
			&i.NetPremiumsWrittenUnit,
			&i.OrdinaryIncome,
			&i.OrdinaryIncomeUnit,
			&i.NetIncome,
			&i.NetIncomeUnit,
			&i.CapitalStock,
			&i.CapitalStockUnit,
			&i.NetAssets,
			&i.NetAssetsUnit,
			&i.TotalAssets,
			&i.TotalAssetsUnit,
			&i.NumberOfEmployees,
			&i.NumberOfEmployeesUnit,
			&i.MajorShareholder1,
			&i.ShareholdingRatio1,
			&i.MajorShareholder2,
			&i.ShareholdingRatio2,
			&i.MajorShareholder3,
			&i.ShareholdingRatio3,
			&i.MajorShareholder4,
			&i.ShareholdingRatio4,
			&i.MajorShareholder5,
			&i.ShareholdingRatio5,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestFinanceByCorporateNumber = `-- name: GetLatestFinanceByCorporateNumber :one
SELECT id, corporate_number, corporate_name_from_number, head_office_location_from_number, corporate_name, head_office_location, accounting_standards, business_year, period_number, sales_revenue, sales_revenue_unit, operating_revenue1, operating_revenue1_unit, operating_revenue2, operating_revenue2_unit, gross_operating_revenue, gross_operating_revenue_unit, ordinary_revenue, ordinary_revenue_unit, net_premiums_written, net_premiums_written_unit, ordinary_income, ordinary_income_unit, net_income, net_income_unit, capital_stock, capital_stock_unit, net_assets, net_assets_unit, total_assets, total_assets_unit, number_of_employees, number_of_employees_unit, major_shareholder1, shareholding_ratio1, major_shareholder2, shareholding_ratio2, major_shareholder3, shareholding_ratio3, major_shareholder4, shareholding_ratio4, major_shareholder5, shareholding_ratio5, created_at, updated_at FROM finances 
WHERE corporate_number = $1 
ORDER BY business_year DESC, period_number DESC 
LIMIT 1
`

func (q *Queries) GetLatestFinanceByCorporateNumber(ctx context.Context, corporateNumber string) (Finance, error) {
	row := q.db.QueryRowContext(ctx, getLatestFinanceByCorporateNumber, corporateNumber)
	var i Finance
	err := row.Scan(
		&i.ID,
		&i.CorporateNumber,
		&i.CorporateNameFromNumber,
		&i.HeadOfficeLocationFromNumber,
		&i.CorporateName,
		&i.HeadOfficeLocation,
		&i.AccountingStandards,
		&i.BusinessYear,
		&i.PeriodNumber,
		&i.SalesRevenue,
		&i.SalesRevenueUnit,
		&i.OperatingRevenue1,
		&i.OperatingRevenue1Unit,
		&i.OperatingRevenue2,
		&i.OperatingRevenue2Unit,
		&i.GrossOperatingRevenue,
		&i.GrossOperatingRevenueUnit,
		&i.OrdinaryRevenue,
		&i.OrdinaryRevenueUnit,
		&i.NetPremiumsWritten,
		&i.NetPremiumsWrittenUnit,
		&i.OrdinaryIncome,
		&i.OrdinaryIncomeUnit,
		&i.NetIncome,
		&i.NetIncomeUnit,
		&i.CapitalStock,
		&i.CapitalStockUnit,
		&i.NetAssets,
		&i.NetAssetsUnit,
		&i.TotalAssets,
		&i.TotalAssetsUnit,
		&i.NumberOfEmployees,
		&i.NumberOfEmployeesUnit,
		&i.MajorShareholder1,
		&i.ShareholdingRatio1,
		&i.MajorShareholder2,
		&i.ShareholdingRatio2,
		&i.MajorShareholder3,
		&i.ShareholdingRatio3,
		&i.MajorShareholder4,
		&i.ShareholdingRatio4,
		&i.MajorShareholder5,
		&i.ShareholdingRatio5,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
