// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Corporation defines model for Corporation.
type Corporation struct {
	// BusinessItems Business items (JSON format)
	BusinessItems *string `json:"business_items"`

	// BusinessSummary Business summary
	BusinessSummary *string `json:"business_summary"`

	// CapitalStock Capital stock
	CapitalStock *int64 `json:"capital_stock"`

	// CloseCause Registration closure reason
	CloseCause *string `json:"close_cause"`

	// CloseDate Registration closure date
	CloseDate *openapi_types.Date `json:"close_date"`

	// CompanySizeFemale Company size (female employees)
	CompanySizeFemale *int `json:"company_size_female"`

	// CompanySizeMale Company size (male employees)
	CompanySizeMale *int `json:"company_size_male"`

	// CompanyUrl Company website URL
	CompanyUrl *string `json:"company_url"`

	// CorporateNumber 13-digit corporate number
	CorporateNumber string `json:"corporate_number"`

	// CreatedAt Created time
	CreatedAt time.Time `json:"created_at"`

	// DateOfEstablishment Date of establishment
	DateOfEstablishment *openapi_types.Date `json:"date_of_establishment"`

	// EmployeeNumber Number of employees
	EmployeeNumber *int `json:"employee_number"`

	// FoundingYear Founding year
	FoundingYear *int `json:"founding_year"`

	// Id Corporation UUID
	Id openapi_types.UUID `json:"id"`

	// Kana Corporation name in katakana
	Kana *string `json:"kana"`

	// Location Head office location
	Location *string `json:"location"`

	// Name Corporation name
	Name string `json:"name"`

	// NameEn Corporation name in English
	NameEn *string `json:"name_en"`

	// NumberOfActivity Number of activity
	NumberOfActivity *string `json:"number_of_activity"`

	// PostalCode Postal code
	PostalCode *string `json:"postal_code"`

	// PrefectureCode Prefecture code (JIS X 0401)
	PrefectureCode *string `json:"prefecture_code"`

	// QualificationGrade Qualification grade
	QualificationGrade *string `json:"qualification_grade"`

	// RepresentativeName Representative name
	RepresentativeName *string `json:"representative_name"`

	// RepresentativePosition Representative position
	RepresentativePosition *string `json:"representative_position"`

	// Status Corporation status
	Status string `json:"status"`

	// UpdateDate Last updated date from gBizINFO
	UpdateDate *openapi_types.Date `json:"update_date"`

	// UpdatedAt Updated time
	UpdatedAt time.Time `json:"updated_at"`
}

// GetCorporationsParams defines parameters for GetCorporations.
type GetCorporationsParams struct {
	// Limit Maximum number of corporations to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of corporations to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// CorporateNumber Filter by corporate number
	CorporateNumber *string `form:"corporate_number,omitempty" json:"corporate_number,omitempty"`

	// Name Filter by corporation name (partial match)
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Prefecture Filter by prefecture
	Prefecture *string `form:"prefecture,omitempty" json:"prefecture,omitempty"`

	// PrefectureCode Filter by prefecture code (JIS X 0401 codes 01-47)
	PrefectureCode *string `form:"prefecture_code,omitempty" json:"prefecture_code,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all corporations
	// (GET /corporations)
	GetCorporations(w http.ResponseWriter, r *http.Request, params GetCorporationsParams)
	// Get corporation by corporate number
	// (GET /corporations/{corporate_number})
	GetCorporationsCorporateNumber(w http.ResponseWriter, r *http.Request, corporateNumber string)
	// Health check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all corporations
// (GET /corporations)
func (_ Unimplemented) GetCorporations(w http.ResponseWriter, r *http.Request, params GetCorporationsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get corporation by corporate number
// (GET /corporations/{corporate_number})
func (_ Unimplemented) GetCorporationsCorporateNumber(w http.ResponseWriter, r *http.Request, corporateNumber string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCorporations operation middleware
func (siw *ServerInterfaceWrapper) GetCorporations(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCorporationsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "corporate_number" -------------

	err = runtime.BindQueryParameter("form", true, false, "corporate_number", r.URL.Query(), &params.CorporateNumber)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "corporate_number", Err: err})
		return
	}

	// ------------- Optional query parameter "name" -------------

	err = runtime.BindQueryParameter("form", true, false, "name", r.URL.Query(), &params.Name)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "name", Err: err})
		return
	}

	// ------------- Optional query parameter "prefecture" -------------

	err = runtime.BindQueryParameter("form", true, false, "prefecture", r.URL.Query(), &params.Prefecture)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "prefecture", Err: err})
		return
	}

	// ------------- Optional query parameter "prefecture_code" -------------

	err = runtime.BindQueryParameter("form", true, false, "prefecture_code", r.URL.Query(), &params.PrefectureCode)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "prefecture_code", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCorporations(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// GetCorporationsCorporateNumber operation middleware
func (siw *ServerInterfaceWrapper) GetCorporationsCorporateNumber(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "corporate_number" -------------
	var corporateNumber string

	err = runtime.BindStyledParameterWithLocation("simple", false, "corporate_number", runtime.ParamLocationPath, chi.URLParam(r, "corporate_number"), &corporateNumber)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "corporate_number", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCorporationsCorporateNumber(w, r, corporateNumber)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/corporations", wrapper.GetCorporations)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/corporations/{corporate_number}", wrapper.GetCorporationsCorporateNumber)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYb2/bxhn/KodbXziAZB39J7H1rnGXVUWWdPkDDHM04UQ+lK4meczd0Y2a6cUkYBiQ",
	"bX2TZtiAAdmcLkXaAB2KoWua7MvQjutvMdyRokmRkpk0QOY3pngP7/e75/9zd7HN/ZAHECiJ23extIfg",
	"U/O4w0XIBVWMB/pnKHgIQjEwi/1IsgCk7DEFvnnjgLQFCxNxfDFdR2YdrXxw/eoV5HLhU3UONzDcoX7o",
	"AW7j3Vs4nryIp5/F09/Hk3/Gk8fx5B8nD+4d/+XZLdxAevXbePJdPP1dPH148tt7x/e/uIW7uIGDyPNo",
	"X++hRAQNrEah3k8qwYIBHjdOKcrI96kYLSE5k8gT69wwvJ7E08/j6XPNYvo4nn5z+Ozey8+f1sG3acgU",
	"9XpScXuvDL6TLKNkOYdskeSvgRN94TZmgTq/sRiTBQoGIAyoxyX0bBpJKENegwGTKjEp0pKRACSASh4U",
	"jv7D44OXnx3UOqOBc6iqi2ZE81hrZG29aa01iYVzB07FzsbnfkiDUU+yT6Dngk+9CiI7iRDSQmglkULg",
	"hx4fAciCO26QWkrOo9bBXIJ4/pUQI+EtxvoY+pIpQDevXS6oeKhUKNutVvpm1eZ+Pd0m8Q+9IPL7IMrA",
	"1nrTYQOmUCaKUtE8vLW2vrF5/sLWNrHW1nEDh1QpEPr7X++S5nb3rrU+fgdXERBAFTg97RGlMydrSDF/",
	"kT/dINttQtqE/Gres5rpVyVEvdjjbg+kon2PyaEPQQX4e/qk3EVFsTkWpEms1/TqmacsVPwV895QmDnV",
	"XAap41QujwKHBYPeCGgFyKV0GZnl3Pb6cHX2Z06Vr2ZFBd282XmvoDVibZPzbv9CcxMs2rzgbG03+1sO",
	"aWYeRPt2Xp9RxJwqM+7RgC6HDqgPiAVojypqpPM04smX8fSBqTtP48lX8eSRyf4H8eTf8fSbePrnePpl",
	"HTN63M6qZ5HK+0AdxF2X2YAyqTyFl3/71+Gzr06mL47+OD38/uD4/tdHf3iWPVtNqw6+PuTZaijiPnxy",
	"9PzTw+d/PX7037njVm7fg6Ceon8aDHSgFMCumweU7zPqnMr4vo5Saiu2z9RoWXxkMoWMVAcn5FJXb5s7",
	"FUr80Cwis1jYmZAmIaQegAAXbBUJWASSCRggtPJB5zr6JSIbxCr2UNZ6BV4pza5VZ9nbEfWYyxIn7A0E",
	"raLyi7wQSoTyDN6tc2ABoQAJgaKK7UOv2j2vFYTKHnp8/+vD/zw9evTkZPqn1wANuWTVMTkHnAnmwQ+/",
	"P/jh718cffrg+NuHRy++q4MvFVWRXB4kqUwxFVbZKgpNharuty5TqVAi4Zg+C7mC+2hwkX3SuXLp6hvs",
	"ulKQysJ8MyXwJguzMePtiAlwcHsXm6Rf6k7SfJdpvNA/FDh3MwDe/whshccagQUuX24mnwZ0ALrWo3c/",
	"7GiaTJmj5YWSlX0QMu2RVskq0UrjIQQ0ZLiN11fJatoIDY1ntOzTDcyLAagqB1WCwT4gijwmlclunofy",
	"36KPmRoibr6gHnKZp0CrENHAQSEdsGCWZvUsZ547Dm7jn4HayVPQ3AT1QYGQuL07z+Tn9A7zIz9t9jSR",
	"AgnFkQAVCY3DtPztCMxwlUQ89pjPtEmSWTM5qEsjT6Wdi59sn0xCDeyzIP1ZbjLGjcWpf56T3GOhHkGL",
	"iqgiyF1XwgKGeUKkDqFLxgioP6rqkqvQKzz7lEfN5rkOjaw8r4RUKEY95FNlD88toDWLroyKT+9chmCg",
	"hri9trn5ShROS98CsIJAJaRFXhOxVEvNC4mI1dy4cO5MPr205leaZIXsWs3t7m92reZG19jnXJVxujqf",
	"yZAHMrlMWSNE/7N5oNJ5g4ahl1bb1kcyKVc5xMJVzHzyyG5k3hHg4jb+Sev0iqeV3u+08k3XOGNIhaAj",
	"07qaEC2XGP0aRRKcciCV+/80jEq7XDXva2+juKIVU+8N/XpBCsJVgVmV9OePl6TVwlbjBt74UfYBIbgZ",
	"r8pV7UxGF6mDdOkDqTSRzbdGpBNoH6cekiD2QaBkLy2X3a7pKlKqSNoSdKCLCC5UmK7+tFD3WnfnE9+4",
	"TimUIdi6My2ktf4IMSWrEu7Sujd7hisz8aVl8MYQShBoxVpH5lJEZrlE1/ml6f20uUkarldP9z82o9RO",
	"FWXPyDc/5kbh7UZMJ9inHnPKhkkbTUNu4y2RK0zGXJ3q6/8/sOfCqyK0lsT5EKini/aCcN4Zgr2HmIvU",
	"EHQDbbgwGxCTKPl0ZDpYEQWBPth8GL9vZMwu+I2W1kXDWwKYzm26YmjiKenC0MP3zpxmUoxuDVtdL6ll",
	"zlApLzvVxMwiqfq7ZsvEzlX57DK3Mz/QE5Pw0svjdqvl6bUhl6q9RbYIHnfH/wsAAP//bWMXyToaAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
