/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check if the API service is healthy and running
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corporations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all corporations
         * @description Retrieve a list of all corporations with optional filtering and pagination
         */
        get: {
            parameters: {
                query?: {
                    /** @description Maximum number of corporations to return */
                    limit?: number;
                    /** @description Number of corporations to skip for pagination */
                    offset?: number;
                    /** @description Filter by corporate number */
                    corporate_number?: string;
                    /** @description Filter by corporation name (partial match) */
                    name?: string;
                    /** @description Filter by prefecture */
                    prefecture?: string;
                    /** @description Filter by prefecture code (JIS X 0401 codes 01-47) */
                    prefecture_code?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of corporations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            corporations?: components["schemas"]["Corporation"][];
                            /** @description Total number of corporations */
                            total?: number;
                            /** @description Limit used for pagination */
                            limit?: number;
                            /** @description Offset used for pagination */
                            offset?: number;
                        };
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corporations/{corporate_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get corporation by corporate number
         * @description Retrieve a specific corporation by its corporate number
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The corporate number (13 digits) */
                    corporate_number: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Corporation found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Corporation"];
                    };
                };
                /** @description Invalid corporate number format */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Corporation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corporations/{corporate_number}/fetch-bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Fetch base/branch offices using OpenAI
         * @description Fetch base/branch offices information for a corporation using OpenAI API.
         *     This endpoint:
         *     1. Gets URLs of official company website pages containing office information
         *     2. Extracts office information from those URLs
         *     3. Saves the extracted information to the database
         *
         */
        post: operations["fetchCorporationBases"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Corporation: {
            /**
             * Format: uuid
             * @description Corporation UUID
             * @example 01906fb7-5e1a-7d89-b8d0-123456789abc
             */
            id: string;
            /**
             * @description 13-digit corporate number
             * @example 1234567890123
             */
            corporate_number: string;
            /**
             * @description Corporation name
             * @example 株式会社サンプル
             */
            name: string;
            /**
             * @description Corporation name in katakana
             * @example カブシキガイシャサンプル
             */
            kana?: string | null;
            /**
             * @description Corporation name in English
             * @example Sample Corporation
             */
            name_en?: string | null;
            /**
             * @description Postal code
             * @example 100-0001
             */
            postal_code?: string | null;
            /**
             * @description Head office location
             * @example 東京都千代田区千代田1-1
             */
            location?: string | null;
            /**
             * @description Prefecture code (JIS X 0401)
             * @example 13
             */
            prefecture_code?: string | null;
            /**
             * @description Corporation status
             * @example 01
             */
            status: string;
            /**
             * Format: date
             * @description Registration closure date
             * @example 2023-12-01
             */
            close_date?: string | null;
            /**
             * @description Registration closure reason
             * @example 解散
             */
            close_cause?: string | null;
            /**
             * @description Representative name
             * @example 田中太郎
             */
            representative_name?: string | null;
            /**
             * @description Representative position
             * @example 代表取締役
             */
            representative_position?: string | null;
            /**
             * Format: date
             * @description Date of establishment
             * @example 2020-01-01
             */
            date_of_establishment?: string | null;
            /**
             * @description Founding year
             * @example 2020
             */
            founding_year?: number | null;
            /**
             * Format: int64
             * @description Capital stock
             * @example 10000000
             */
            capital_stock?: number | null;
            /**
             * @description Number of employees
             * @example 100
             */
            employee_number?: number | null;
            /**
             * @description Company size (male employees)
             * @example 60
             */
            company_size_male?: number | null;
            /**
             * @description Company size (female employees)
             * @example 40
             */
            company_size_female?: number | null;
            /**
             * @description Business items (JSON format)
             * @example ["ソフトウェア開発", "システム運用"]
             */
            business_items?: string | null;
            /**
             * @description Business summary
             * @example ITソリューション事業
             */
            business_summary?: string | null;
            /**
             * @description Company website URL
             * @example https://example.com
             */
            company_url?: string | null;
            /**
             * @description Qualification grade
             * @example A
             */
            qualification_grade?: string | null;
            /**
             * @description Number of activity
             * @example 1
             */
            number_of_activity?: string | null;
            /**
             * Format: date
             * @description Last updated date from gBizINFO
             * @example 2023-12-01
             */
            update_date?: string | null;
            /**
             * Format: date-time
             * @description Created time
             * @example 2023-12-01T09:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Updated time
             * @example 2023-12-01T09:00:00Z
             */
            updated_at: string;
            /** @description Base/branch offices of the corporation */
            bases?: components["schemas"]["Base"][];
        };
        Base: {
            /**
             * Format: uuid
             * @description Base UUID
             * @example 01906fb7-5e1a-7d89-b8d0-123456789abc
             */
            id: string;
            /**
             * Format: uuid
             * @description Corporation UUID this base belongs to
             * @example 01906fb7-5e1a-7d89-b8d0-123456789abc
             */
            corporation_id: string;
            /**
             * @description 13-digit corporate number
             * @example 1234567890123
             */
            corporate_number: string;
            /**
             * @description Base/branch office name
             * @example 東京本社
             */
            base_name?: string | null;
            /**
             * @description Country code (ISO 3166-1 alpha-2)
             * @example JP
             */
            country_code: string;
            /**
             * @description Postal code
             * @example 100-0001
             */
            postal_code?: string | null;
            /**
             * @description Base location
             * @example 東京都千代田区千代田1-1
             */
            location?: string | null;
            /**
             * @description Phone number
             * @example 03-1234-5678
             */
            phone_number?: string | null;
            /**
             * @description Fax number
             * @example 03-1234-5679
             */
            fax_number?: string | null;
            /**
             * Format: date-time
             * @description When the data was obtained
             * @example 2023-12-01T09:00:00Z
             */
            data_obtained_at: string;
            /**
             * @description Source URL of the data
             * @example https://gbiz-info.go.jp/
             */
            data_source_url: string;
            /**
             * @description Whether this is the head office
             * @example true
             */
            is_head_office: boolean;
            /**
             * Format: date-time
             * @description Created time
             * @example 2023-12-01T09:00:00Z
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Updated time
             * @example 2023-12-01T09:00:00Z
             */
            updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Health status of the service
                         * @example ok
                         */
                        status: string;
                    };
                };
            };
        };
    };
    fetchCorporationBases: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The corporate number */
                corporate_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully fetched and saved base/branch offices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Successfully fetched and saved base/branch offices */
                        message?: string;
                        /** @example 5 */
                        bases_count?: number;
                        /** @example [
                         *       "https://example.com/company/offices",
                         *       "https://example.com/about/locations"
                         *     ] */
                        urls_found?: string[];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Invalid corporate number format */
                        error?: string;
                    };
                };
            };
            /** @description Corporation not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Corporation not found */
                        error?: string;
                    };
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Failed to fetch bases information */
                        error?: string;
                    };
                };
            };
        };
    };
}
